### ISSUE TITLE
IAGA2002 writer doesn't follow standard

### ISSUE THREAD

**Issue by greglucas** [usgs/geomag-algorithms#186]
The IAGA2002 writer doesn't guarantee a space in the numeric columns.

> The format for field elements is 4(1X, F9.2)

[IAGA2002 link](https://www.ngdc.noaa.gov/IAGA/vdat/IAGA2002/iaga2002format.html)

The geoelectric fields produce some anomalous values that are not nan's that mess this up because they are 10 digits.
The timestamp: 2016-07-27 17:27:23.000 produces an IAGA output of:

> 2016-07-27 17:27:23.000 209   2147000.002147000.00  99999.00  99999.00

_format_values should change from:

`        return '{0.tm_year:0>4d}-{0.tm_mon:0>2d}-{0.tm_mday:0>2d} ' \
                '{0.tm_hour:0>2d}:{0.tm_min:0>2d}:{0.tm_sec:0>2d}.{1:0>3d} ' \
                '{0.tm_yday:0>3d}   ' \
                '{2:10.2f}{3:10.2f}{4:10.2f}{5:10.2f}\n'.format(
                tt, int(time.microsecond / 1000),
                *[self.empty_value if numpy.isnan(val) else val
                        for val in values])`

to:

`        return '{0.tm_year:0>4d}-{0.tm_mon:0>2d}-{0.tm_mday:0>2d} ' \
                '{0.tm_hour:0>2d}:{0.tm_min:0>2d}:{0.tm_sec:0>2d}.{1:0>3d} ' \
                '{0.tm_yday:0>3d}   ' \
                ' {2:9.2f} {3:9.2f} {4:9.2f} {5:9.2f}\n'.format(
                tt, int(time.microsecond / 1000),
                *[self.empty_value if numpy.isnan(val) else val
                        for val in values])`

**Comment by jmfee-usgs** [comment]
Hi Greg, thanks for reporting this issue.  You're correct that the spec uses `9.2f` and the suggested fix looks good.

However, I'm a little concerned this will also break our IAGA output in these cases because the overflowing numbers would cause the line to go beyond 70 characters (the old format has the same problem if the number extended beyond 10 decimals).  While this project's IAGA2002 parser can handle that, I'm concerned other projects may be less flexible and unable to use the data.
```
         1         2.        3.        4.        5         6         7
1234567890123456789012345678901234567890123456789012345678901234567890
2016-07-27 17:27:23.000 209    2147000.00 2147000.00  99999.00  99999.00
2016-07-27 17:27:23.500 209       -27.63     74.16  88888.00  88888.00
```

- Do you think (in addition to your proposed fix) we should add a check during output that looks for values outside the range, and optionally removes them?  The value 2147000.00 looks a lot like a truncated and scaled max value for a 32-bit integer 2,147,483,647...

- Can you also include details about the parameters used to find these spikes?  I tried BOU E-field via the web service, but don't see the same numbers:
https://geomag.usgs.gov/ws/edge/?id=BOU&starttime=2016-07-27T17:27:00Z&endtime=2016-07-27T17:28:00&sampling_period=1&elements=E-E,E-N

**Comment by greglucas** [comment]
Jeremy, yes you're correct this will break another one of IAGA's rules with the 70 character limit which I overlooked.

Others have run into this issue as well and suggested wrapping the floats in your own class for outputting.
https://bugs.python.org/issue20811

> Do you think (in addition to your proposed fix) we should add a check during output that looks for values outside the range, and optionally removes them? The value 2147000.00 looks a lot like a truncated and scaled max value for a 32-bit integer 2,147,483,647...

Yes, I think this would be valuable as well. Although perhaps unnecessary overhead at this point in the code? Maybe this could all be fixed upstream a little ways with what values are even being put into the writer in the first place. Like you say, I think this is an anomalous 32-bit integer problem, possibly with casting somewhere else.

That is interesting, if you extend your time window to one hour then the problem occurs for me, but your one-minute data did not cause it. Try this:
`https://geomag.usgs.gov/ws/edge/?id=BOU&starttime=2016-07-27T17:00:00Z&endtime=2016-07-27T17:59:59&sampling_period=1s&elements=E-E,E-N`

```
2016-07-27 17:27:20.000 209     99999.00  99999.00  99999.00  99999.00
2016-07-27 17:27:21.000 209     99999.00  99999.00  99999.00  99999.00
2016-07-27 17:27:22.000 209     99999.00  99999.00  99999.00  99999.00
2016-07-27 17:27:23.000 209   2147000.002147000.00  99999.00  99999.00
2016-07-27 17:27:24.000 209        74.16    -27.62  99999.00  99999.00
2016-07-27 17:27:25.000 209        74.18    -27.62  99999.00  99999.00
2016-07-27 17:27:26.000 209        74.25    -27.56  99999.00  99999.00
2016-07-27 17:27:27.000 209        74.30    -27.49  99999.00  99999.00
2016-07-27 17:27:28.000 209        74.33    -27.41  99999.00  99999.00
```

**Comment by erigler-usgs** [comment]
I'll just add that something very similar to what @greglucas describes in the previous comment happens when using the Geomag-Algorithms tools instead of the Geomag web service (that is, depending on the exact starttime and endtime specified, one may or may not get the 214700.00 values returned).

**Comment by greglucas** [comment]
Yes, that is correct @erigler-usgs. This is also not the only place that this occurs. There are a few other times in 2016 as well. I came across this because I was downloading the entire year's worth of data and it failed multiple times on these values.

@jmfee-usgs, Another interesting observation is that there are ".500" timestamps that occur sometimes. So, perhaps there is some anomalous timestamp stored on the edge server? i.e. One extra entry was put in somewhere and the obspy routines aren't sure how to return that to the user when requesting sequential data over a given time range?

**Comment by jmfee-usgs** [comment]
The value appears to be returned by EDGE, and not actually stored.  In this case the value actually occurs at 23.500 seconds but depending on how the data is requested it is either reported at 23.0, 23.5, or 24 seconds.  I'm working with @ketchum-usgs to resolve that problem.

Since this is a data problem, going to merge and resolve the data problem separately.
