### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#254]
- as new major version
- support 3.6+ (drop 2.7, <3.6)

Tools
- pylint
- pytest
- flask/gunicorn for web services

Update Packages
- `algorithms` for algorithms, subpackages?
- `io` for formats
- `util` for utilities

Other comments?

**Comment by erigler-usgs** [comment]
I'm not sure I understand all that is being proposed above, but it looks like more than just adapting/updating the existing package to Py3.

First, re. "Tools", inclusion of pylint and pytest seems fine, but why? I assume this means we drop flake8 and nosetests.

Second, can you elaborate on how flask/gunicorn would be used? Is this as a way to bypass JS requirements and simplify our development by keeping everything in Python?

Finally, re. "Update Packages", are you suggesting we break up Geomag-Algorithms into these subpackages, and possibly sub-sub-packages for different algorithms? This sounds like a lot of thought an effort, is there a compelling reason to include this otherwise sensible change now?

**Comment by jmfee-usgs** [comment]
@erigler-usgs : Yes, I've proposed more than just python 3.  When we drop support for python 2, that's a non-backward compatible change and we'll bump the major version (to 1.0).  This _could_ be an opportunity to consider other changes.

Pylint and Pytest are more widely used, and NumPy/SciPy are migrating from nose to pytest.  Pylint also does static analysis, beyond just code formatting, and can identify duplicate or error-prone code.

Flask is a micro-framework for web services, and it works with WSGI like the existing web service.  Gunicorn is just a server for running WSGI applications, and we would use that to run the services.

The existing factories have grown and have a fair amount of overlap.  Looking back, I think we could simplify how factories work and reorganize parsing/formatting to be more transparent for users (one file based factory, supporting multiple format plugins...).  Looking forward, there are planned changes to the internal algorithm api to better support stream processing.  Re-packaging now sets us up for a more manageable project in the future, before we add more code that needs to be updated.

I think we also need to revisit code standards, and maybe consider auto formatting like autopep8 to reduce developer effort.

**Comment by erigler-usgs** [comment]
If my earlier "thumbs up" response wasn't clear, I am ok with moving forward with this plan.

Just to emphasize something discussed briefly offline, let's take care to make a clean break from the old geomag-algorithms. In addition to the new major version proposed, this should include some very obvious language in docs that we are breaking backward compatibility.

**Comment by jmfee-usgs** [comment]
This is completed in the master branch, at least the version and tools.  Repackaging will wait for now.
