### ISSUE TITLE
add sq/dist algorithm readme

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#64]
link from relevant documentation places

**Comment by emcwhirter-usgs** [comment]
For documentation purposes --> Since this algorithm produces 3 different output channels, do we want to name it after all of them, or is 1 sufficient to imply the others, or some other combination?

For example, so far we have:
 - Delta F Algorithm
 - XYZ Algorithm

Do we call this one SQ Algorithm, Solar Quiet Algorithm, SQDist Algorithm, SVSQDist Algorithm, Solar Quiet and Disturbance Algorithm? I think "Solar Quiet and Disturbance Algorithm" most accurately describes it, but other feedback is welcome.

**Comment by jmfee-usgs** [comment]
I think your suggested title (solar quiet and disturbance algorithm) sounds good.
The class could be SqDistAlgorithm
