### ISSUE TITLE
make sqdist algorithm use state

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#76]
If the first requested time doesn't match the next_starttime SqDistAlgorithm property, the state is considered invalid and discarded (get_input_interval and process_one methods).

option, when using state:
- do not process any data before next_starttime.  In get_input_interval, if endtime is before next_starttime, don't clear the state but also in process_one return an empty stream.
- in get_input_interval, if the requested starttime is after next_starttime (instead of equal) return an interval that starts at next_starttime.

**Comment by emcwhirter-usgs** [comment]
- in process_one throw an AlgorithmException instead of clearing state
- add method to clear state
- in get_input_interval:
  - if end < next_starttime, throw AlgorithmException
  - if start > next_starttime, return (next_starttime, end)
  - if start < next_starttime, return (next_starttime, end)
  - still default to (start-3months, end) if no state

**Comment by emcwhirter-usgs** [comment]
It makes more sense to check for end < next_starttime in `can_produce_data` and return False instead of throwing an AlgorithmException in `get_input_interval`. This would skip over the older gaps and save some processing.
